baseurl = "https://2020.gophercon.sg/"
languageCode = "en-SG"
title = "GopherCon Singapore 2020"
theme = "gopherconsg-2017"

[params]
name = "GopherCon Singapore"
description = "GopherCon Singapore is a Go programming language (Golang) conference in Southeast Asia."
ogimage = "gopherconsg2020-og-d.png"

# Navigation
[params.navigation.brand]
png = "gopherconsg2020-long-d.png"
